name: ci

on:
  push:
    branches: [main]
  pull_request:

env:
  KSP_ROOT: D:\\KSP
  CKAN_DEPS: |
    Harmony2 ExtraPlanetaryLaunchpads ClickThroughBlocker
    Kopernicus USI-LS
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download ckan.exe
        run: gh release download --repo KSP-CKAN/CKAN --pattern ckan.exe -O ckan.exe

          
      - name: Configure CKAN
        run: |
          ./ckan.exe instance fake --asroot --set-default KSP ${{ env.KSP_ROOT }} 1.12.5 --game KSP --MakingHistory 1.9.1 --BreakingGround 1.7.1
          ./ckan.exe update --asroot
          ./ckan.exe compat add --asroot 1.12
          ./ckan.exe compat add --asroot 1.11
          ./ckan.exe compat add --asroot 1.10
          ./ckan.exe compat add --asroot 1.9
          ./ckan.exe compat add --asroot 1.8
        shell: bash
        
      - name: Download KSP Libs
        run: |
          curl -sSL https://github.com/KSPModdingLibs/KSPLibs/raw/main/KSP-1.12.5.zip -o D:\\ksp.zip
          unzip -q D:\\ksp.zip -d ${{ env.KSP_ROOT }}
        shell: bash

      - name: Install CKAN dependencies
        run: ./ckan.exe install --asroot --headless --no-recommends ${{ env.CKAN_DEPS }}

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - run: dotnet restore -verbosity detailed
      - run: dotnet build

      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/assemble-release@main




  # build:
  #   run-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: KSPModdingLibs/KSPBuildTools/.github/actions/setup-ckan@main
  #     - uses: KSPModdingLibs/KSPBuildTools/.github/actions/install-dependencies@main
  #       with:
  #         dependency-identifiers: ${{ env.CKAN_DEPS }}

  #     - name: Download KSP Libs
  #       run: |
  #         wget --quiet https://github.com/KSPModdingLibs/KSPLibs/raw/main/KSP-1.12.5.zip -O /tmp/ksp.zip
  #         unzip -q /tmp/ksp.zip -d /tmp/ksp
  #         echo 'KSP_ROOT=/tmp/ksp' >> "$GITHUB_ENV"

  #     - name: nuget restore
  #       run: |
  #         nuget restore BackgroundResourceProcessing.sln -Verbosity detailed

  #     - uses: lhotari/action-upterm@v1

  #     - uses: KSPModdingLibs/KSPBuildTools/.github/actions/assemble-release@main
