name: ci

on:
  push:
    branches: [main]
  pull_request:

env:
  CKAN_DEPS: |
    Harmony2 ExtraPlanetaryLaunchpads ClickThroughBlocker
    Kopernicus USI-LS

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/setup-ckan@main
      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/install-dependencies@main
        with:
          dependency-identifiers: ${{ env.CKAN_DEPS }}

      - name: Download KSP Libs
        run: |
          wget --quiet https://github.com/KSPModdingLibs/KSPLibs/raw/main/KSP-1.12.5.zip -O /tmp/ksp.zip
          unzip -q /tmp/ksp.zip -d /tmp/ksp
          echo 'KSP_ROOT=/tmp/ksp' >> "$GITHUB_ENV"

      - name: nuget restore
        run: |
          nuget restore BackgroundResourceProcessing.sln -Verbosity detailed

      - uses: lhotari/action-upterm@v1

      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/assemble-release@main
