name: ci

on:
  push:
    branches: [main]
  pull_request:

env:
  CKAN_DEPS: |
    Harmony2 ExtraPlanetaryLaunchpads ClickThroughBlocker
    Kopernicus USI-LS

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download ckan.exe
        runs: gh release download --repo KSP-CKAN/CKAN --pattern ckan.exe -o ckan.exe

      - name: Download KSP Libs
        runs: |
          wget --quiet https://github.com/KSPModdingLibs/KSPLibs/raw/main/KSP-1.12.5.zip -O /tmp/ksp.zip
          unzip -q /tmp/ksp.zip -d /tmp/ksp
          echo 'KSP_ROOT=/tmp/ksp' >> "$GITHUB_ENV"
          
      - name: Configure CKAN
        runs: |
          ./ckan.exe instance fake --set-default KSP${{ env.KSP_ROOT }} 1.12.5 --game KSP --MakingHistory 1.9.1 --BreakingGround 1.7.1
          ./ckan.exe update
          ./ckan.exe compat add 1.12
          ./ckan.exe compat add 1.11
          ./ckan.exe compat add 1.10
          ./ckan.exe compat add 1.9
          ./ckan.exe compat add 1.8

      - name: Install CKAN dependencies
        runs: ./ckan.exe install --headless --no-recommends ${{ env.CKAN_DEPS }}

      - name: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - runs: dotnet restore -verbosity detailed
      - runs: dotnet build

      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/assemble-release@main




  # build:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: KSPModdingLibs/KSPBuildTools/.github/actions/setup-ckan@main
  #     - uses: KSPModdingLibs/KSPBuildTools/.github/actions/install-dependencies@main
  #       with:
  #         dependency-identifiers: ${{ env.CKAN_DEPS }}

  #     - name: Download KSP Libs
  #       run: |
  #         wget --quiet https://github.com/KSPModdingLibs/KSPLibs/raw/main/KSP-1.12.5.zip -O /tmp/ksp.zip
  #         unzip -q /tmp/ksp.zip -d /tmp/ksp
  #         echo 'KSP_ROOT=/tmp/ksp' >> "$GITHUB_ENV"

  #     - name: nuget restore
  #       run: |
  #         nuget restore BackgroundResourceProcessing.sln -Verbosity detailed

  #     - uses: lhotari/action-upterm@v1

  #     - uses: KSPModdingLibs/KSPBuildTools/.github/actions/assemble-release@main
