name: ci

on:
  push:
  pull_request:

env:
  CKAN_DEPS: |
    Harmony2 ExtraPlanetaryLaunchpads ClickThroughBlocker
    Kopernicus USI-LS

jobs:
  build:
    using: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/setup-ckan@main

      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/install-dependencies@main
        with:
          dependency-identifiers: ${env.CKAN_DEPS}

      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/compile@main
        with:
          build-configuration: Release

      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/assembly-release@main

  test:
    using: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/setup-ckan@main

      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/install-dependencies@main
        with:
          dependency-identifiers: ${env.CKAN_DEPS}

      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/compile@main
        with:
          build-configuration: Debug

      - name: Run Tests
        run: |
          dotnet test -p:ManagedRelativePath=KSP_x64_Data/Managed
